
package efficom.runningjoe.ws.userapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserApiPortType", targetNamespace = "http://efficom/runningjoe/ws/UserApi/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserApiPortType {
    /**
     * 
     * @param email
     * @param name
     * @param password
     * @return
     *     returns int
     */
    @WebMethod(action = "http://efficom/runningjoe/ws/UserApi/register")
    @WebResult(partName = "return")
    public int register(
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "email", partName = "email")
        String email,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param name
     * @param password
     * @return
     *     returns int
     */
    @WebMethod(action = "http://efficom/runningjoe/ws/UserApi/login")
    @WebResult(partName = "return")
    public int login(
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param oldpassword
     * @param user
     * @param newpassword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://efficom/runningjoe/ws/UserApi/changepassword")
    @WebResult(partName = "return")
    public String changepassword(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "oldpassword", partName = "oldpassword")
        String oldpassword,
        @WebParam(name = "newpassword", partName = "newpassword")
        String newpassword);

    /**
     * 
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://efficom/runningjoe/ws/UserApi/forgottenpassword")
    @WebResult(partName = "return")
    public String forgottenpassword(
        @WebParam(name = "email", partName = "email")
        String email);

    /**
     * 
     * @param number
     * @param lang
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://efficom/runningjoe/ws/UserApi/errordescription")
    @WebResult(partName = "return")
    public String errordescription(
        @WebParam(name = "lang", partName = "lang")
        String lang,
        @WebParam(name = "number", partName = "number")
        int number);

    /**
     * 
     * @param scorevalue
     * @param name
     * @return
     *     returns int
     */
    @WebMethod(action = "http://efficom/runningjoe/ws/UserApi/recordscore")
    @WebResult(partName = "return")
    public int recordscore(
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "scorevalue", partName = "scorevalue")
        int scorevalue);

    /**
     * 
     * @param limit
     * @param offset
     * @return
     *     returns efficom.runningjoe.ws.userapi.ArrayOfScore
     */
    @WebMethod(action = "http://efficom/runningjoe/ws/UserApi/highscores")
    @WebResult(partName = "return")
    public ArrayOfScore highscores(
        @WebParam(name = "limit", partName = "limit")
        int limit,
        @WebParam(name = "offset", partName = "offset")
        int offset);

    /**
     * 
     * @param limit
     * @param offset
     * @return
     *     returns efficom.runningjoe.ws.userapi.ArrayOfString
     */
    @WebMethod(action = "http://efficom/runningjoe/ws/UserApi/highscoresstring")
    @WebResult(partName = "return")
    public ArrayOfString highscoresstring(
        @WebParam(name = "limit", partName = "limit")
        int limit,
        @WebParam(name = "offset", partName = "offset")
        int offset);

    /**
     * 
     * @param id
     * @return
     *     returns int
     */
    @WebMethod(action = "http://efficom/runningjoe/ws/UserApi/range")
    @WebResult(partName = "return")
    public int range(
        @WebParam(name = "id", partName = "id")
        int id);

}
